-- the large credits illustrations, cut into tiles
-- generated by tools/cut_illustrations.py from tools/atlas_dump.json

ForeverUIGlue = ForeverUIGlue or {}
ForeverUIGlue.illustrations = {
	[0] = { width = 1425, height = 966, tiles = {
		{ "interface\\ForeverUI\\credits\\creditsscreen-keyart-0-c60-1", 1.000000, 0.943359, 1024 },
		{ "interface\\ForeverUI\\credits\\creditsscreen-keyart-0-c60-2", 0.783203, 0.943359, 401 },
	} },
	[1] = { width = 1425, height = 966, tiles = {
		{ "interface\\ForeverUI\\credits\\creditsscreen-keyart-1-1", 1.000000, 0.943359, 1024 },
		{ "interface\\ForeverUI\\credits\\creditsscreen-keyart-1-2", 0.783203, 0.943359, 401 },
	} },
	[2] = { width = 1425, height = 966, tiles = {
		{ "interface\\ForeverUI\\credits\\creditsscreen-keyart-2-1", 1.000000, 0.943359, 1024 },
		{ "interface\\ForeverUI\\credits\\creditsscreen-keyart-2-2", 0.783203, 0.943359, 401 },
	} },
}
