# -*- coding: utf-8 -*-
# This file is part of mod-forever-ui.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

"""Valid character customization choices, computed without running the engine.

A choice's number is its rank among the valid choices. Making the engine cycle a setting
(CycleCharCustomization) to list them redraws the character at each step, so the engine's
rules are reproduced here on its CharSections data: cells [race][sex][section][variation]
[color] (0x4F3BA0; sections 0 skin, 1 face, 2 facial hair, 3 hair, 4 underwear). Character
creation and the barber shop apply the per-setting rules to this table (0x4EB150 skin,
0x4EB710 face, 0x4F0490 hair style, 0x4EB500 hair color, 0x4EBCA0 facial hair).

Writes data/glue/Interface/GlueXML/ForeverUIGlueChoices.lua:
  ForeverUIGlue.choice["RACE FILE"][sex 0/1] = {
      [section] = { n = count, [variation] = "string" }, facialHairs = n }
one character per color: "." no row, else 1 (valid except for death knights) + 2 (valid
for death knights). The same table goes to data/addon/ForeverUI/BarberShopData.lua
(ForeverUI.AppearanceChoices) for the in-game barber, since the addon cannot read login
screen files. Also checks that each valid hair style has its BarberShopStyle.dbc row.
"""
import argparse
import io
import os
import struct
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from foreverui import mpq  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_CLIENT = r"E:\world of warcraft 3.3.5a hd"
OUTPUT = os.path.join(ROOT, "data", "glue", "Interface", "GlueXML", "ForeverUIGlueChoices.lua")
ADDON_OUTPUT = os.path.join(ROOT, "data", "addon", "ForeverUI", "BarberShopData.lua")
BS = chr(92)
PLAYABLE = (1, 2, 3, 4, 5, 6, 7, 8, 10, 11)
SECTIONS = 5


# Rows of a client DBC as field tuples, and a function reading its string block at an offset.
def read_dbc(client, name):
    d = client.read("DBFilesClient" + BS + name)
    if d[:4] != b"WDBC":
        raise SystemExit("%s illisible" % name)
    n, fields, size, _ = struct.unpack("<4I", d[4:20])
    strings = d[20 + n * size:]

    def chain(o):
        return strings[o:strings.index(b"\0", o)].decode("utf-8", "replace")
    return [struct.unpack_from("<%dI" % fields, d, 20 + i * size) for i in range(n)], chain


# CharSections flags check (0x4F39A0): bit 1 set, bits 4 and 8 clear; for a death knight
# (class 6, 0x4F3A40): bit 1 set, bit 4 or 16 set, bit 8 clear.
def isAvailable(flags, death_knight):
    if death_knight:
        return bool(flags & 1) and bool(flags & 0x14) and not flags & 8
    return bool(flags & 1) and not flags & 0xC


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--client", default=DEFAULT_CLIENT, help="dossier du client 3.3.5")
    options = parser.parse_args()
    # The client as it is, without our archive
    client = mpq.open_client(os.path.join(options.client, "Data"), "enUS", ignore=("patch-Z.MPQ",))

    races, chain = read_dbc(client, "ChrRaces.dbc")
    file = {v[0]: chain(v[11]).upper() for v in races if v[0] in PLAYABLE}
    cells = defaultdict(dict)          # (race, sex, section) -> {(variation, color): flags}
    for v in read_dbc(client, "CharSections.dbc")[0]:
        race, sex, section, flags, variation, color = v[1], v[2], v[3], v[7], v[8], v[9]
        if race in file and section < SECTIONS:
            cells[(race, sex, section)][(variation, color)] = flags
    facialHairs = defaultdict(int)
    for v in read_dbc(client, "CharacterFacialHairStyles.dbc")[0]:
        if v[0] in file:
            facialHairs[(v[0], v[1])] += 1

    header = [
        "-- valid appearance choices, by race, sex, section and variation: one",
        "-- character per color (\".\" no row, else 1: valid outside death knight,",
        "-- + 2: valid for death knight)",
        "-- generated by tools/customization_choices.py from the 3.3.5 client's",
        "-- CharSections.dbc and CharacterFacialHairStyles.dbc",
    ]
    rows = []
    total = 0
    for race in sorted(file, key=lambda r: file[r]):
        rows.append('\t["%s"] = {' % file[race])
        for sex in (0, 1):
            rows.append("\t\t[%d] = {" % sex)
            for section in range(SECTIONS):
                c = cells.get((race, sex, section), {})
                var_count = max((var for var, _ in c), default=-1) + 1
                variations = []
                for var in range(var_count):
                    colors = [col for v2, col in c if v2 == var]
                    n = max(colors, default=-1) + 1
                    text = ""
                    for col in range(n):
                        d = c.get((var, col))
                        text += "." if d is None else str((1 if isAvailable(d, False) else 0) + (2 if isAvailable(d, True) else 0))
                    variations.append('[%d] = "%s"' % (var, text))
                    total += n
                rows.append("\t\t\t[%d] = { n = %d, %s }," % (section, var_count, ", ".join(variations)))
            rows.append("\t\t\tfacialHairs = %d," % facialHairs[(race, sex)])
            rows.append("\t\t},")
        rows.append("\t},")
    rows.append("}")
    io.open(OUTPUT, "w", encoding="utf-8", newline="\n").write("\n".join(
        header + ["", "ForeverUIGlue = ForeverUIGlue or {}", "ForeverUIGlue.choice = {"] + rows + [""]))
    print("choix : %d races, %d cases -> %s" % (len(file), total, os.path.relpath(OUTPUT, ROOT)))

    # The in-game barber: the same table
    io.open(ADDON_OUTPUT, "w", encoding="utf-8", newline="\n").write("\n".join(
        header + ["-- (copy for the in-game barber shop)", "",
                  "ForeverUI = ForeverUI or {}", "ForeverUI.AppearanceChoices = {"] + rows + [""]))
    print("coiffeur : -> %s" % os.path.relpath(ADDON_OUTPUT, ROOT))
    # Check: each valid hair style has its BarberShopStyle row (the barber looks it up after
    # each step, 0x52F760)
    styles = read_dbc(client, "BarberShopStyle.dbc")[0]
    style_rows = {(v[37], v[38], v[1], v[39]) for v in styles}
    for race in sorted(file, key=lambda r: file[r]):
        for sex in (0, 1):
            c = cells.get((race, sex, 3), {})
            for death_knight in (False, True):
                valid = sorted({var for (var, col), dr in c.items() if isAvailable(dr, death_knight)})
                missing = [s for s in valid if (race, sex, 0, s) not in style_rows]
                if missing:
                    print("   %s %d%s : coiffures sans ligne : %s" % (file[race], sex, " (chevalier)" if death_knight else "", missing))


if __name__ == "__main__":
    main()
