# -*- coding: utf-8 -*-
# This file is part of mod-forever-ui.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

"""Cuts the large credits illustrations into tiles for 3.3.5.

CreditsScreen-KeyArt-<n> is 1425 x 966 on a 2048 x 1024 sheet, and the 3.3.5 client does
not show an image wider than 1024 (see foreverui/blp.py). Scaling it down to 1024 would lose
a third of its detail on a screen where it is enlarged, so it is cut at full resolution into
tiles at most 1024 wide, placed side by side on screen.

For each entry of ILLUSTRATIONS: export its sheet through the wow.export bridge, read its
region from tools/atlas_dump.json and cut it into tiles. Each tile sits at the top left of a
power-of-two image (the rest transparent), written uncompressed with its mipmaps to
data/art/interface/ForeverUI/credits/ (plus a .png). Then write
data/glue/Interface/GlueXML/ForeverUIGlueIllustrations.lua.

wow.export must be running with its source loaded (bridge on port 9455).
"""
import io
import json
import os
import sys
import urllib.parse
import urllib.request

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from foreverui import blp  # noqa: E402

BRIDGE = "http://127.0.0.1:9455"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "tools", "atlas_dump.json")
ART = os.path.join(ROOT, "data", "art", "interface", "ForeverUI", "credits")
TABLE = os.path.join(ROOT, "data", "glue", "Interface", "GlueXML", "ForeverUIGlueIllustrations.lua")
STAGING = os.path.join(os.environ.get("TEMP", "."), "foreverui_export")
BS = chr(92)
TILE = 1024

# Expansion number -> atlas element (the c60 variant when camelot has one).
ILLUSTRATIONS = {
    0: "creditsscreen-keyart-0-c60",
    1: "creditsscreen-keyart-1",
    2: "creditsscreen-keyart-2",
}


# GET request to the wow.export bridge; returns the decoded JSON reply.
def _request(path, params):
    url = BRIDGE + path + "?" + urllib.parse.urlencode(params, doseq=True)
    with urllib.request.urlopen(url, timeout=900) as r:
        return json.loads(r.read().decode("utf-8"))


# Smallest power of two not below n.
def _pow2(n):
    p = 1
    while p < n:
        p *= 2
    return p


def main():
    if not _request("/status", {})["ready"]:
        _request("/load-source", {})
        raise SystemExit("la source de wow.export se charge, relancer dans une minute")
    os.makedirs(STAGING, exist_ok=True)
    os.makedirs(ART, exist_ok=True)
    index = json.load(io.open(INDEX, encoding="utf-8"))["results"]
    matches = {r["atlas"].lower(): r for r in index}

    rows = [
        "-- the large credits illustrations, cut into tiles",
        "-- generated by tools/cut_illustrations.py from tools/atlas_dump.json",
        "",
        "ForeverUIGlue = ForeverUIGlue or {}",
        "ForeverUIGlue.illustrations = {",
    ]
    for extension, name in sorted(ILLUSTRATIONS.items()):
        r = matches.get(name)
        if not r:
            raise SystemExit("absent de l'index : %s" % name)
        sheet = r["file"].lower()
        res = _request("/export", [("dest", STAGING), ("file", sheet)])
        if res["failed"]:
            raise SystemExit("export en echec : %s" % res)
        with io.open(os.path.join(STAGING, sheet.replace("/", os.sep)), "rb") as f:
            width, height, rgba, _ = blp.decode(f.read())
        image = Image.frombytes("RGBA", (width, height), bytes(rgba))
        reg = r["region"]
        w, h = reg["width"], reg["height"]
        isWhole = image.crop((reg["left"], reg["top"], reg["left"] + w, reg["top"] + h))

        tiles = []
        x = 0
        while x < w:
            tw = min(TILE, w - x)
            piece = isWhole.crop((x, 0, x + tw, h))
            W, H = _pow2(tw), _pow2(h)
            canvas = Image.new("RGBA", (W, H), (0, 0, 0, 0))
            canvas.paste(piece, (0, 0))
            full = canvas.convert("RGBa")
            mips = []
            mw, mh = W, H
            while mw > 1 or mh > 1:
                mw, mh = max(1, mw // 2), max(1, mh // 2)
                mips.append((mw, mh, full.resize((mw, mh), Image.LANCZOS).convert("RGBA").tobytes()))
            base = "%s-%d" % (name, len(tiles) + 1)
            with io.open(os.path.join(ART, base + ".blp"), "wb") as f:
                f.write(blp.encode(W, H, canvas.tobytes(), mips))
            canvas.save(os.path.join(ART, base + ".png"))
            path = BS.join(["interface", "ForeverUI", "credits", base])
            tiles.append((path, tw / float(W), h / float(H), tw))
            print("   %-36s %d x %d dans %d x %d" % (base, tw, h, W, H))
            x += tw

        rows.append("\t[%d] = { width = %d, height = %d, tiles = {" % (extension, w, h))
        for path, u2, v2, tw in tiles:
            rows.append('\t\t{ "%s", %.6f, %.6f, %d },' % (path.replace(BS, BS + BS), u2, v2, tw))
        rows.append("\t} },")
    rows += ["}", ""]
    io.open(TABLE, "w", encoding="utf-8", newline="\n").write("\n".join(rows))
    print("table : %d illustrations -> %s" % (len(ILLUSTRATIONS), os.path.relpath(TABLE, ROOT)))


if __name__ == "__main__":
    main()
