# -*- coding: utf-8 -*-
# This file is part of mod-forever-ui.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

"""Modern client data the login screens need, written to
data/glue/Interface/GlueXML/ForeverUIGlueData.lua.

Class colors: camelot colors a character card's class with GetClassColor (ChrClasses.db2,
ClassColorR/G/B). 3.3.5 glue has no such function, and GetCharacterInfo returns only the
class name in the client language, so the table is keyed by the ChrClasses names and
gives the token and the color.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from foreverui import db2  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLASSES = os.path.join(os.path.expanduser("~"), "wow.export", "dbfilesclient", "chrclasses.db2")
OUTPUT = os.path.join(ROOT, "data", "glue", "Interface", "GlueXML", "ForeverUIGlueData.lua")

# 3.3.5 classes
CLASSES_335 = ("WARRIOR", "PALADIN", "HUNTER", "ROGUE", "PRIEST", "DEATHKNIGHT",
               "SHAMAN", "MAGE", "WARLOCK", "DRUID")


def main():
    rows = [
        "-- modern client data for the login screens",
        "-- generated by tools/glue_data.py",
        "",
        "ForeverUIGlue = ForeverUIGlue or {}",
        "-- class name (ChrClasses, English) -> token, color (ClassColorR/G/B)",
        "ForeverUIGlue.CLASSES = {",
    ]
    n = 0
    for _, v in db2.read(CLASSES, (0, 1, 2, 3)):
        token = v[1]
        if token not in CLASSES_335:
            continue
        r, g, b = v[-6], v[-5], v[-4]
        names = sorted(set(x for x in (v[0], v[2], v[3]) if x))
        for name in names:
            rows.append('\t["%s"] = { "%s", %.4f, %.4f, %.4f },' % (name, token, r / 255.0, g / 255.0, b / 255.0))
        n += 1
    # Death knights are missing from the modern ChrClasses: use the 3.3.5 client's own color
    # (RAID_CLASS_COLORS, Interface/FrameXML/Constants.lua in patch-enus-2).
    rows.append('	["Death Knight"] = { "DEATHKNIGHT", 0.7700, 0.1200, 0.2300 },')
    n += 1
    rows += ["}", ""]
    io.open(OUTPUT, "w", encoding="utf-8", newline="\n").write("\n".join(rows))
    print("donnees : %d classes -> %s" % (n, os.path.relpath(OUTPUT, ROOT)))


if __name__ == "__main__":
    main()
