# -*- coding: utf-8 -*-
# This file is part of mod-forever-ui.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

"""Guild tabard colors, read from the textures of the 3.3.5 client.

Camelot tints the Social button with the tabard background color and its small emblem
with the emblem color (C_GuildInfo.GetGuildTabardInfo). The 3.3.5 client lacks that
function: it only gives the tabard texture NAMES (GetGuildTabardFileNames), and the colors
are painted in those images (Background_<background>_TU_U, Emblem_<pattern>_<color>_TU_U).
So each color is read from the image.

The textures carry shading (cloth folds, emblem relief), so a plain average is too dark.
We keep the average of the brightest quarter of the opaque pixels: the hue as seen in light.

Output: data/addon/ForeverUI/TabardColors.lua, regenerated on each run.
"""
import io
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from foreverui import blp, mpq  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLIENT = r"E:\world of warcraft 3.3.5a hd\Data"
OUTPUT = os.path.join(ROOT, "data", "addon", "ForeverUI", "TabardColors.lua")


# Color of a texture as (r, g, b) in 0..1, from its brightest opaque pixels.
# chain: client archives; name: texture path.
def color(chain, name):
    width, height, rgba, _ = blp.decode(chain.read(name))
    pixels = []
    for i in range(0, len(rgba), 4):
        r, v, b, a = rgba[i], rgba[i + 1], rgba[i + 2], rgba[i + 3]
        if a > 200:
            pixels.append((0.299 * r + 0.587 * v + 0.114 * b, r, v, b))
    pixels.sort(reverse=True)
    top = pixels[:max(1, len(pixels) // 4)]
    n = float(len(top))
    return tuple(round(sum(p[k] for p in top) / n / 255.0, 3) for k in (1, 2, 3))


def main():
    chain = mpq.open_client(CLIENT, "enUS")
    backgrounds, emblems = {}, {}
    for name in chain.names():
        down = name.lower()
        m = re.search(r"guildemblems.background_(\d+)_tu_u\.blp$", down)
        if m:
            backgrounds.setdefault(int(m.group(1)), name)
        m = re.search(r"guildemblems.emblem_(\d+)_(\d+)_tu_u\.blp$", down)
        if m:
            emblems.setdefault(int(m.group(2)), name)
    rows = [
        "-- generated by tools/tabard_colors.py from the 3.3.5 client's textures",
        "-- (Background_<background>_TU_U, Emblem_<design>_<color>_TU_U): do not edit",
        "-- by hand.",
        "",
        "local ForeverUI = ForeverUI or {}",
        "_G.ForeverUI = ForeverUI",
        "",
        "ForeverUI.TabardColors = {",
        "\tbackground = {",
    ]
    for k in sorted(backgrounds):
        r, v, b = color(chain, backgrounds[k])
        rows.append("\t\t[%d] = { %s, %s, %s }," % (k, r, v, b))
    rows += ["\t},", "\temblem = {"]
    for k in sorted(emblems):
        r, v, b = color(chain, emblems[k])
        rows.append("\t\t[%d] = { %s, %s, %s }," % (k, r, v, b))
    rows += ["\t},", "}", ""]
    with io.open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(rows))
    print("tabards : %d fonds, %d couleurs d'embleme -> %s" % (len(backgrounds), len(emblems), os.path.relpath(OUTPUT, ROOT)))


if __name__ == "__main__":
    main()
