# -*- coding: utf-8 -*-
# This file is part of mod-forever-ui.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

"""Shape of each WotLK talent node for the Camelot talent screen.

Camelot draws a SQUARE node for a talent that gives an active spell (SpendSquare) and a
ROUND one for a passive (SpendCircle). The 3.3.5 API does not tell: GetTalentInfo returns
name, icon, tier, column and ranks, not the spell. The server DBC files do:

  TalentTab.dbc  tab and its background (BackgroundFile: "MageArcane"...), the same name
                 as the 4th return of GetTalentTabInfo
  Talent.dbc     tab, tier and column (0-based), rank 1 spell
  Spell.dbc      Attributes (field 4): SPELL_ATTR0_PASSIVE = 0x40; a passive that learns
                 a spell (effect 36, LEARN_SPELL) gives an active spell, so it is square too

Output: data/addon/ForeverUI/TalentsData.lua, the SQUARE talents by tab background then
"tier:column" (1-based, like GetTalentInfo); all others are round. For each square talent
it also lists the spells it puts in the spellbook, so it can be dragged to an action bar:
its rank spells (Talent.dbc fields 4-12) or, for a talent that learns spells, the learned
spells (EffectTriggerSpell, fields 116-118, where the effect is 36); Mangle learns
Mangle (Bear) and Mangle (Cat). The UI finds them in the spellbook by GetSpellLink.

Usage: talent_shapes.py [dbc_folder]
"""
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(ROOT, "data", "addon", "ForeverUI", "TalentsData.lua")
DBC = sys.argv[1] if len(sys.argv) > 1 else r"D:\Serveur WoW\server_hard\bin\RelWithDebInfo\Data\dbc"

PASSIVE = 0x40
LEARN_SPELL = 36          # SPELL_EFFECT_LEARN_SPELL
TRIGGER_SPELL = 116         # Spell.dbc: EffectTriggerSpell[3], fields 116-118


# Read a WDBC file: returns its rows (tuples of uint32) and a function that reads
# a string of the string block by offset.
def read(name):
    d = open(os.path.join(DBC, name), "rb").read()
    assert d[:4] == b"WDBC", name
    n, fields, size, _ = struct.unpack_from("<IIII", d, 4)
    strings_start = 20 + n * size

    def chain(o):
        finish = d.index(b"\0", strings_start + o)
        return d[strings_start + o:finish].decode("utf-8")

    rows = [struct.unpack_from("<%dI" % fields, d, 20 + i * size) for i in range(n)]
    return rows, chain


def main():
    tabs, tab_string = read("TalentTab.dbc")
    backgrounds = {o[0]: tab_string(o[23]) for o in tabs}

    spells, _ = read("Spell.dbc")
    by_id = {s[0]: s for s in spells}

    talents, _ = read("Talent.dbc")
    squares = {}
    talent_spells = {}
    for t in talents:
        tab, tier, column, rank1 = t[1], t[2], t[3], t[4]
        background = backgrounds.get(tab)
        sort = by_id.get(rank1)
        if not background or not sort:
            continue
        active = not (sort[4] & PASSIVE) or LEARN_SPELL in sort[71:74]
        if active:
            key = "%d:%d" % (tier + 1, column + 1)
            squares.setdefault(background, set()).add(key)
            ids = []
            for rank in t[4:13]:
                s = by_id.get(rank)
                if not s:
                    continue
                if LEARN_SPELL in s[71:74]:
                    for e in range(3):
                        if s[71 + e] == LEARN_SPELL and s[TRIGGER_SPELL + e]:
                            ids.append(s[TRIGGER_SPELL + e])
                else:
                    ids.append(rank)
            if ids:
                talent_spells.setdefault(background, {}).setdefault(key, [])
                for i in ids:
                    if i not in talent_spells[background][key]:
                        talent_spells[background][key].append(i)

    rows = [
        "-- ForeverUI: talent node shapes (Camelot's screen).",
        "-- GENERATED by tools/talent_shapes.py from the server DBCs -- do not",
        "-- edit by hand. SQUARE talents (an active spell), by tab background",
        "-- (GetTalentTabInfo, 4th return) then \"tier:column\"; the others",
        "-- are ROUND (passives).",
        "",
        "ForeverUI = ForeverUI or {}",
        "ForeverUI.TalentsSquares = {",
    ]
    for background in sorted(squares):
        # One slot can hold several talents (pet trees): the set keeps a single key
        keys = ", ".join('["%s"] = true' % c for c in sorted(squares[background]))
        rows.append('\t["%s"] = { %s },' % (background, keys))
    rows.append("}")
    rows += [
        "",
        "-- spells each square talent puts in the spellbook (ranks, or learned",
        "-- spells), by tab background then \"tier:column\"",
        "ForeverUI.TalentsSpells = {",
    ]
    for background in sorted(talent_spells):
        keys = ", ".join('["%s"] = { %s }' % (c, ", ".join(str(i) for i in talent_spells[background][c]))
                         for c in sorted(talent_spells[background]))
        rows.append('	["%s"] = { %s },' % (background, keys))
    rows.append("}")
    open(OUTPUT, "w", encoding="utf-8", newline="\n").write("\n".join(rows) + "\n")
    total = sum(len(v) for v in squares.values())
    print("%d talents carres sur %d, dans %d onglets -> %s" % (total, len(talents), len(squares),
                                                               os.path.relpath(OUTPUT, ROOT)))


if __name__ == "__main__":
    main()
